name: Testing action

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository name
        run: echo "MWT_REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - run: echo "${{ env.MWT_REPOSITORY_NAME }}"
